#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/application
- name: Run application
  docker_container:
    name: my-api
    image: mickaelpre/devops_project-simple-api
    networks: 
      - name: my_network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3