name: Build and Push Docker Images

on:
  workflow_run:
    workflows:
      - Test Backend CI
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      # Checkout the GitHub code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to Docker Hub
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # Build and push the backend Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: "${{ secrets.DOCKER_USERNAME }}/simple-api:latest"
          push: true

      # Build and push the database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: "${{ secrets.DOCKER_USERNAME }}/database:latest"
          push: true

      # Build and push the HTTP server Docker image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: "${{ secrets.DOCKER_USERNAME }}/httpd:latest"
          push: true
