name: Test Backend CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the GitHub code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: 17
