name: Test Backend CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the GitHube codee
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: 17

        # Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=Micky404_Devops_project -Dsonar.organization=micky404 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: simple-api



